version: "3"

services:
#   server:
#     build: ./DockerfileServer/
#     ports:
#       - "127.0.0.1:8000:8000"
#       - "127.0.0.1:9999:9999"
#     depends_on:
#       - postgres
#     links:
#       - postgres

#   indexer:
#     build: ./DockerfileIndexer/
#     depends_on:
#       - postgres
#     links:
#       - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
