name: CI
on: [push]

jobs:

  cancel:
    runs-on: ubuntu-latest
    name: Cancel Previous Runs
    if: always()
    steps:
      - uses: styfle/cancel-workflow-action@d57d93c3a8110b00c3a2c0b64b8516013c9fd4c9
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"

  build-docker-server:
    runs-on: ubuntu-latest
    name: Build docker image for the server
    continue-on-error: false
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_PERSONAL_USERNAME }}
          password: ${{ secrets.DOCKER_PERSONAL_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          tags: anuragprafulla/hermes_server:${{ github.sha }}
          push: true
          file: Dockerfile.server
          build-args: GIT_COMMIT_HASH=${{ github.sha }}

  build-docker-indexer:
    runs-on: ubuntu-latest
    name: Build docker image for the indexer
    continue-on-error: false
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          tags: anuragprafulla/hermes_server:${{ github.sha }}
          push: true
          file: Dockerfile.indexer
          build-args: GIT_COMMIT_HASH=${{ github.sha }}
